### ISSUE TITLE
Type in CarbonDioxide 

### ISSUE THREAD

**Issue by Joralmi** [mariapoveda/vicinity-ontology-adapters#18]
The property adapters:C02Concentration should be adapters:C**O**2Concentration

**Comment by mariapoveda** [comment]
Thanks for spotting that. I checked and the error was only in the diagram, the ontology was OK, so you can continue using the ontology. We'll update the diagram version online shortly.

**Comment by mariapoveda** [comment]
Now the figure is ok too. Thanks again.
