### ISSUE TITLE
Add illuminance property

### ISSUE THREAD

**Issue by Joralmi** [mariapoveda/vicinity-ontology-adapters#20]
adapters:Illuminance under adapters:LuminusFlux

**Comment by enercdev** [comment]
https://github.com/mariapoveda/vicinity-ontology-adapters/commit/545a978d616357ba4e1c8fb23875ef5a7fad2614

**Comment by enercdev** [comment]
adapters:Illuminance under adapters:LuminusFlux not available in production environment.

**Comment by mariapoveda** [comment]
What do you mean by not available in production?

I see it at http://iot.linkeddata.es/def/adapters#Illuminance

**Comment by enercdev** [comment]
Yes, but not available for use in the VICINITY repository of production environment.

**Comment by mariapoveda** [comment]
I see. It should be updated by @kostelni I think.
