### ISSUE TITLE
Add forecast properties

### ISSUE THREAD

**Issue by Joralmi** [mariapoveda/vicinity-ontology-adapters#21]
adapters:WeatherForecast
adapters:PVForecast

Not sure under which class should be placed, if none is related then add adapters:Forecast

**Comment by mariapoveda** [comment]
What is the meaning of PV in PVForecast?

Could WeatherForecast be placed in AmbientProperty?

**Comment by Joralmi** [comment]
PVForecast would return an estimate production of energy of a PV
I am not sure if ambientProperty is suitable, is it only for indoor properties or can be used for weather conditions too?

**Comment by mariapoveda** [comment]
Could adapters:PVForecast be an instance of adapters:Power? Is it about energy forecast?

I think AmbientProperty is general enough, now it has indoor environmental propeorties but also solar radiation, temperature, etc...

**Comment by Joralmi** [comment]
Alright then I think you can place both forecasts under the classes you suggested:
adapters:PVForecast instance of adapters:Power
adapters:WeatherForecast instance of AmbientProperty
