### ISSUE TITLE
Remove properties

### ISSUE THREAD

**Issue by Joralmi** [mariapoveda/vicinity-ontology-adapters#26]
Please remove the following properties that are duplicated or unnecessary:
adapters:ActualDCPower
adapters:ActualDCVoltage
adapters:ActualDCCurrent
adapters:ChargeStatus

**Comment by mariapoveda** [comment]
@Joralmi which ones are duplicated among them? It would be better to keep one and add synonyms for the duplicates.

For the unnecessary, I need to check whether they are needed in other use case before deleting.

**Comment by Joralmi** [comment]
All of these properties are duplicated by adapters:<device><property>. Where device is for instance battery and property is any of the duplicated properties I mentioned in the issue.

**Comment by mariapoveda** [comment]
A pattern for canonical instances is proposed as future improvement. For now duplicates can coexist as one is the generic version of the specific ones (for each device).
