### ISSUE TITLE
New properties to be added [SHAR-Q]

### ISSUE THREAD

**Issue by Joralmi** [mariapoveda/vicinity-ontology-adapters#37]
We need the following properties to described the new devices added to the ontology:
Timestamp --> OperationalStatus
Reset --> OperationalStatus
MeterValues --> Power
InverterPVActualReactivePowerL1 --> Power
InverterPVActualReactivePowerL2 --> Power
InverterPVActualReactivePowerL3 --> Power
InverterPVActualActivePowerL1 --> Power
InverterPVActualActivePowerL2 --> Power
InverterPVActualActivePowerL3 --> Power

**Comment by mariapoveda** [comment]
How do you plan to use the "Timestamp" and "MeterValues" properties?

**Comment by nekon1979** [comment]
We need the following properties as described bellow added to the ontology for SaMMY:
pH --> decimal number ( values 0 to 14) 
ORP(Oxidation-Reduction potential )  --> decimal number  (volts)

**Comment by mariapoveda** [comment]
@nekon1979  I added a new issue for these properties https://github.com/mariapoveda/vicinity-ontology-adapters/issues/38

It is better to have different discussions and issues for each requirement.

**Comment by Joralmi** [comment]
After the clarifications, it is decided that we need to add only:

InverterPVActualReactivePowerL1 --> Power
InverterPVActualReactivePowerL2 --> Power
InverterPVActualReactivePowerL3 --> Power
InverterPVActualActivePowerL1 --> Power
InverterPVActualActivePowerL2 --> Power
InverterPVActualActivePowerL3 --> Power

The property MeterValues --> Power stays TBD

**Comment by mariapoveda** [comment]
The properties have been created without the "PV" in the name. That is, adapters:InverterActualActivePowerL2. Is that ok or they have to have the "PV" part? @Joralmi

**Comment by Joralmi** [comment]
Please keep the PV in the name, it is helpful to know the type of device
