### ISSUE TITLE
We need the following properties as described bellow added to the ontology for SaMMY:

### ISSUE THREAD

**Issue by mariapoveda** [mariapoveda/vicinity-ontology-adapters#38]
We need the following properties as described bellow added to the ontology for SaMMY:
pH --> decimal number ( values 0 to 14) 
ORP(Oxidation-Reduction potential )  --> decimal number  (volts)

_Originally posted by @nekon1979 in https://github.com/mariapoveda/vicinity-ontology-adapters/issues/37#issuecomment-494054307_

**Comment by mariapoveda** [comment]
@nekon1979 could the properties needed be classified under any category from those in http://iot.linkeddata.es/def/adapters/resources/images/properties1.png ?

For examp ORP is a power related property?

**Comment by nekon1979** [comment]
@mariapoveda  The two specific measurements are related to water polution.
As the catregories presented at schema (http://iot.linkeddata.es/def/adapters/resources/images/properties1.png) it's not seem can be associated with any of the existing categories
Both PH and ORP are Water measurements 
maybe http://iot.linkeddata.es/def/adapters/index-en.html#WaterEnergyMeter  for ORP is more suitable ?

**Comment by mariapoveda** [comment]
What is the meaning of pH, is https://en.wikipedia.org/wiki/PH ?

**Comment by nekon1979** [comment]
Exactly. pH is a scale used to specify the water-based solution

**Comment by mariapoveda** [comment]
The new properties are included in the ontology. I will let you know when the latest version is online.

**Comment by mariapoveda** [comment]
@nekon1979  it is now uploaded.

**Comment by nekon1979** [comment]
Thank you @mariapoveda  for the suppport
