### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by AndrejSeben** [mariapoveda/vicinity-ontology-adapters#40]
"adapters:InverterAccumulatedActiveEnergyConsumptio"
should be 
"adapters:InverterAccumulatedActiveEnergyConsumption"

**Comment by mariapoveda** [comment]
I can't find this in http://iot.linkeddata.es/def/adapters#InverterAccumulatedActiveEnergyConsumption

Where did you find it @AndrejSeben?

**Comment by mariapoveda** [comment]
No response for this issue.
