### ISSUE TITLE
Ontology

### ISSUE THREAD

**Issue by NenadStojanovicGitHub** [mariapoveda/vicinity-ontology-adapters#43]
Hello,

I was instructed by Carmen (Atos) to post this request here

For the Open Call proposal MyBigFitnessTwin, we need to model some devices (sensors) which will send data (separately) to be integrated in the Cloud

We selected four devices, which should be modelled properly (ontology-based) in order to enable interoperability.	 

1. Smartwatch
First, we are sending data from the fitness trackers (smartwatch Polar M600). The collected dataset consists of the Data points with the following structure:
•	Timestamp – time when the data point is generated 
•	Exercise Type – the name of the exercise (e.g. plank, pull ups)
•	Heartrate value – derivation of HRV (heart rate variability), measured using optical method) 
•	Accuracy – how accurate is the HR measurement process (due to optical sensing)

2. Smartscale
Example: https://consumer.huawei.com/en/accessories/smart-scale/
Parameters:
•	body fat percentage
•	total body water percentage
•	visceral fat rating
•	basal metabolic rate
•	muscle mass
•	body mass index
•	bone mineral content
•	protein

3. Blood pressure tracker (continuous blood pressure monitor)
Example: https://omronhealthcare.com/generation-zero/
Parameters:
•	Time
•	SYS
•	DIA
•	Pulse

4. Glucometer
Example: https://www.contourplusone.in/
There are many parameters that can be obtained (id, sequence, offset, mgdl, time, status, sampleType, sampleLocation, contextInfoFollows, meal, devMac.), but we would focus on:
•	time
•	mgdl (sugar level)

We are thinking about some additional devices (more fitness related) but we want first to have these modelled and then it would be easier to add a new device

Thanks

**Comment by mariapoveda** [comment]
@NenadStojanovicGitHub are the devices sensors, actuators or both?

We already have adapters:BloodPressureMonitor do you really need a new one for the Blood pressure tracker?

We already have adapters:WeightScale do you really need a new one for Smartscale ?

**Comment by mariapoveda** [comment]
What do you mean by "time" for the blood pressure tracker and the glucometer? the timestamp of the data?

I am not sure how do you plan to use the smart watch data but what we can represent are properties. Maybe we can ask Andrea and Peter for the complex data types.

Properties that already exsited:
adapters:HeartRate 
adapters:DiastolicBloodPressure 
adapters:SystolicBloodPressure

**Comment by NenadStojanovicGitHub** [comment]
Hello Maria 
Thanks for answers
I agree that we can use adapters:BloodPressureMonitor for blood pressure.

Regarding  adapters:WeightScale: is it "only" representing weight of a person
We need not only weight, but also some of those:
•	body fat percentage
•	total body water percentage
•	visceral fat rating
•	basal metabolic rate
•	muscle mass
•	body mass index
•	bone mineral content
•	protein
I assume that these are properties that should be modelled in addition

**Comment by mariapoveda** [comment]
Regarding https://github.com/mariapoveda/vicinity-ontology-adapters/issues/43#issuecomment-508454048

The properties are included. The question about the Smartscale vs WeightScale is whether you also need a new device or could classify yours under WeightScale. No problem to create a new one. 

Please, indicate also whether all the devices you mentioned are sensors or actuators or both.

**Comment by mariapoveda** [comment]
After 3 months with no news about this issue it is closed.
