### ISSUE TITLE
Add BARTER adapter components to the ontology

### ISSUE THREAD

**Issue by pesicsasa** [mariapoveda/vicinity-ontology-adapters#45]
At the moment, the actions from our adapter define the following: "affects": "adapters:DimmingLevel". We would like to request new adapters to be created in the ontology.

Our BARTER adapter defines three things: barter-micropayment-bitcoin, barter-micropayment-dash, barter-data-storage. We have the need for three adapters: BitcoinWallet, DashWallet and Repository. 

Since BARTER adapter is the only one that is interracting with these things, we are not sure how to define them in the ontology (they are not exposed to other VICINITY devices or users).

**Comment by mariapoveda** [comment]
Hi @pesicsasa 

just to check: BitcoinWallet, DashWallet and Repository are devices or properties?

**Comment by ikovico** [comment]
Hi @mariapoveda , they are not physical devices nor properties. They are more in a form of service or logical representations which has it's own properties. Similar to an account in the bank ( it's not a physical device but it has properties such as balance, account number, etc,), wallet has it's own properties such as balance, funding address, private key, etc... The similar situation is with repository as well.

**Comment by mariapoveda** [comment]
Thanks. Could you list then for each service its name and its properties (those needed to be added to the ontology)?

**Comment by ikovico** [comment]
List of services with their properties, actions and events:

**service name** : _DashWallet_
**properties**: 
_balance_ (provides info about wallet balance), 
_funding_address_ (provides wallet funding address), 
_payment_address_ (provides wallet payment address info),
_private_key_ (provides wallet private key), 
_ticker_ (provides info about currency value for a wallet),
_send_payment_ (sends transaction from a wallet)
**actions**: 
_wallet_setup_ (creates a wallet), 
_wallet_recover_ (recovers a wallet)
**events**: 
_dash_payments_  (provides info about transactions of a wallet)

**service name** : _BitcoinWallet_
**properties**: 
_balance_  provides info about wallet balance), 
_funding_address_  (provides wallet funding address), 
_payment_address_ (provides wallet payment address info),
_private_key_ (provides wallet private key), 
_ticker_  (provides info about currency value for a wallet),
_send_payment_  (sends transaction from a wallet)
**actions**: 
_wallet_setup_ (creates a wallet) 
_wallet_recover_ (recovers a wallet)
**events**: 
_bitcoin_payments_ (provides info about transactions of a wallet)

**service name**: _Repository_
**properties**: 
_create_asset_ (creates a digital asset),
_read_asset_by_key_  (reads a digital asset by unique key),
_update_asset_  (updates a digital asset by unique key),
_invalidate_asset_  (invalidates a digital asset by unique key),
_read_assets_by_key_range_  (reads  digital assets by key range)
_read_asset_history_  (reads a digital asset history)
_couchdb_query_assets_  (reads digital assets by arbitrary query/selector)
**actions**: 
_repository_setup_ (creates a repository)

More detailed view where each property includes list of fields it has (output fields) is attached in the JSON document (within the ZIP archive). If you need additional info, do not hesitate to contact me.

[BARTER-Ontology.zip](https://github.com/mariapoveda/vicinity-ontology-adapters/files/3573264/BARTER-Ontology.zip)

**Comment by mariapoveda** [comment]
In the way we model, we just need to add the services and the affected properties by properties, actions or events. @pesicsasa  Could you confirm if the following properties would be right? See that there are some questions in bold.


Service name : DashWallet
_properties_ (Affected or observed, not properties as actions to get data:
wallet balance
wallet funding address
wallet payment address info
wallet private key
**currency value for a wallet ---> which kind of information is this? Do you have an example?**
**wallet transaction ??**
_from actions:_
wallet
_from events_:
**wallet transaction ??**

service name : BitcoinWallet
_from properties_:
wallet balance
wallet funding address
wallet payment address info
wallet private key
**currency value for a wallet, ---> which kind of information is this? Do you have an example?**
**wallet transaction ??**
_from actions_:
wallet
_from events_:
**wallet transaction ??**

service name: Repository
_from properties_:
digital asset
digital asset history
_from actions_:
**repository ??**

**Comment by ikovico** [comment]
Hi ok, I think I understand the idea now. Here is the final set in that case (I have removed unnecessary items and updated remaining) :

Service name : DashWallet
properties (Affected or observed, not properties as actions to get data):
balance
funding address
private key
value (ratio between FIAT (i.e. USD) and cryptocurrency, i.e. 1DASH equals 80USD)  
transactions
from actions:
**wallet**

In this case **wallet** is the highest in hierarchy and listed properties affected or observed are wallet's properties.

service name : BitcoinWallet
properties (Affected or observed, not properties as actions to get data):
balance
funding address
private key
value 
transaction(s)
from actions:
**wallet**

In this case **wallet** is the highest in hierarchy and listed properties affected or observed are wallet's properties.

service name: Repository
from properties:
digital asset(s)
from actions:
**repository**

In this case **repository** is the highest in hierarchy and listed properties affected or observed are repository's properties.

**Comment by mariapoveda** [comment]
sorry, I edited you comment by mistake.

**Comment by mariapoveda** [comment]
The new elements are now available at http://iot.linkeddata.es/def/adapters#

**Comment by ikovico** [comment]
Thank you!

**Comment by ikovico** [comment]
Hi,

sorry for the late update, but we need one more property added for Wallet service named: "WalletPaymentForward" if that's ok with you?

**Comment by mariapoveda** [comment]
the new property is in the online version of the ontology now: http://iot.linkeddata.es/def/core#WalletPaymentForward

**Comment by ikovico** [comment]
Thank you. Just one more question. Based on the [documentation](https://github.com/vicinityh2020/vicinity-agent/blob/master/docs/TD.md#ontology-annotation) we can only use ontology annotations from [here]( https://api.vicinity.bavenir.eu/api/repository/annotations). ( all known ontology annotations can be found via Neighborhood Manager service, please see end of the page)

However the models you have added are not yet available. Is there something we need to do in order to be able to use them within our adapter?

**Comment by mariapoveda** [comment]
Maybe the Neighborhood Manager service needs to be updated with the new ontology . Any idea @MooXo @voravec @AndreaCimminoArriaga

**Comment by ikovico** [comment]
Any update on this? The NM is still unable to process new annotations.

**Comment by AndreaCimminoArriaga** [comment]
Sorry for my late response. I think NM only suggest what you can use, but in the end you can use whatever you want to use in your description file. Nevertheless, if that is not the case, and the NM needs to be modified then BVR should be contacted.

**Comment by Joralmi** [comment]
Hello all, sorry for the delay, I was not aware of this issue.
So, I see that the semantic repository does not contain the latest ontology. I am going to contact the person that maintains it so he can update it.
Once the update is done, the NM will read the new values, and so it will be possible to register devices of the type "BitcoinWallet" and all the new you have defined.

**Comment by mariapoveda** [comment]
@pesicsasa it should be working now.

**Comment by ikovico** [comment]
Thanks everyone for your support.
